### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by vikingsraven** [tgree/stm_layout#14]
HI just found this program as i have started to use STM32f767zit6.
ran the command stm_layout -c stm32f767zit6
got the following
`  File "/home/mark/.local/bin/stm_layout", line 8, in <module>
    sys.exit(_main())
  File "/home/mark/.local/lib/python3.8/site-packages/stm_layout/stm_layout.py", line 375, in _main
    chip = chip_stm.make_chip(part)
  File "/home/mark/.local/lib/python3.8/site-packages/stm_layout/chip_stm.py", line 250, in make_chip
    gpio    = gpios[gpio_key]
KeyError: 'PC14/OSC32'
`
python 3.8.10
Linux Mint 20.2 Cinnamon Kernel  5.4.0-94-generic

**Comment by salkinium** [comment]
Can confirm on macOS, probably missing an additional `.split("/")` somewhere.

EDIT: Maybe in these three lines: https://github.com/tgree/stm_layout/blob/master/stm_layout/chip_stm.py#L244

**Comment by tgree** [comment]
@vikingsraven, thanks for the report and thanks @salkinium for the fix!  Sorry for the delay, somehow this never showed up in my inbox.  I've pushed the fix along with some minor pylint fixes and published a version 0.1.3 on PyPI as well.
